# Generated by Django 3.2.23 on 2023-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='id',
            field=models.BigAutoField(auto_created=True, default='orca-32455', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finding',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unique_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
    ]
